sudo: false
cache:
  directories:
    - node_modules
language: "node_js"
node_js:
  - "node"
  - "lts/*"
matrix: 
  include:
    - node_js: "lts/*"
      env: STATIC_CHECKS=true
script:
  - |
    if [ "${STATIC_CHECKS}" = "true" ]; then
      # Just perform static checks and exit
      eslint --max-warnings 0 .
      exit 0
    fi
  - nyc mocha
after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls
